### ISSUE TITLE
ffho-luci-autoupdater-wifi-fallback: Fehler beim Bauen

### ISSUE THREAD

**Issue by rubo77** [FreifunkHochstift/ffho-packages#4]
Ich bekomme beim Bauen von 2016.2.x diesen Fehler:

```
Configuring gluon-config-mode-mesh-vpn.
/media/workspace/gluon-build/gluon/Makefile:411: recipe for target 'package_install' failed
make[4]: *** [package_install] Error 255
make[4]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
/media/workspace/gluon-build/gluon/Makefile:435: recipe for target 'image' failed
make[3]: *** [image] Error 2
make[3]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
/media/workspace/gluon-build/gluon/Makefile:479: recipe for target 'image/CPE510' failed
make[2]: *** [image/CPE510] Error 2
make[2]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
/media/workspace/gluon-build/gluon/Makefile:482: recipe for target 'call_image/CPE510' failed
make[1]: *** [call_image/CPE510] Error 2
make[1]: Leaving directory '/media/workspace/...
```

Ich habe versucht die Firmware zu bauen, indem ich das paket ergänzt habe und dann wie immer baue (mit make update)

Siehe  https://forum.freifunk.net/t/fork-von-ffho-autoupdater-wifi-fallback-gesucht/11423/31

**Comment by rubo77** [comment]
Wahrscheinlich weil ich in `modules` master hatte, ich versuche noch mal diese Einstellungen: https://git.c3pb.de/freifunk-pb/site-ffho/blob/stable/modules

**Comment by rubo77** [comment]
I get the same error with this setting:

```
#ffho-luci-autoupdater-wifi-fallback
PACKAGES_FFHO_REPO=http://git.c3pb.de/freifunk-pb/ffho-packages.git
PACKAGES_FFHO_BRANCH=v2016.2.x
PACKAGES_FFHO_COMMIT=33f44ef1cae86899f30614f69e10b692c82e4545

```

**Comment by kb-light** [comment]
Du möchtest (aktuell) `gluon-luci-autoupdater` durch `ffho-luci-autoupdater-wifi-fallback` ersetzen.

**Comment by rubo77** [comment]
Ah ok, das stand nirgendwo. habs im anderen issue #5  mit angemerkt. 

Das heisst, dieses Paket ist ein abgewandeltes autoupdater paket. Sind denn hier alle patches am autoupdater auch eingeflossen? Da waren ja einige in den letzten Monaten.

**Comment by rubo77** [comment]
hat nichts gebracht, selber Fehler.

Ich habe auch versucht den patch anzuwenden, aber das scheint nichts zu bringen.

muss man den patch noch irgendwo hinkopieren? z.B.

    cp 0001-openwrt-patch-iw.patch patches/packages/openwrt/

**Comment by kb-light** [comment]
nicht kopieren, der patch muss auf den gluon branch/commit angewendet werden (git am), wie in #5 geschrieben.

**Comment by rubo77** [comment]
Der build-fehler kam wohl daher, dass ich vergessen hatte in dem ersten string `GLUON_SITE_FEEDS` das kürzel `ffho` zu ergänzen
